name = "sci-ai"
compatibility_date = "2023-06-28"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".next"

[build]
command = "npm run build"
watch_dir = "./app"

[env.production]
routes = [
  { pattern = "/", zone_name = "your-domain.com" }
]

[triggers]
crons = []
