name = "sci-ai"
compatibility_date = "2023-06-28"
compatibility_flags = ["nodejs_compat"]

# Build output directory for Cloudflare Pages
pages_build_output_dir = ".next"

[build]
command = "npm run build"
watch_dir = "./app"
node_version = "18"

[site]
bucket = ".next"

[env.production]
routes = [
  { pattern = "/", zone_name = "your-domain.com" }
]

[triggers]
crons = []
